on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v1.0.7
          token: ${{ secrets.token_for_ci_cd_practice }}
           
  deploy:
    needs: [build]
    name: Upload on firebase app distributor
    runs-on: ubuntu-latest
    steps:
    - uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          release_notes: "a new version"
          file: "build/app/outputs/apk/debug/*.apk"

