name: Demo App Android Release

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build Web and Deploy on the hosting
    runs-on: ubuntu-latest
    steps:
      - run: flutter pub get
      - run: flutter build web
      - run: firebase deploy --only hosting


